"""One-shot helper: compute true transitive closures of the project's
direct deps from the installed Python and emit requirements.lock /
rag_api/requirements.lock.

Run from the repo root:  python scripts/_gen_locks.py
Delete after use — not part of the runtime."""

from __future__ import annotations

import importlib.metadata as m
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DIRECT_ROOT = ["requests", "python-frontmatter", "PyYAML", "ollama", "watchdog"]
DIRECT_RAG = ["fastapi", "uvicorn", "chromadb", "pydantic", "requests", "python-multipart"]


def closure(roots):
    seen, stack = {}, list(roots)
    while stack:
        name = stack.pop().lower()
        if name in seen:
            continue
        try:
            dist = m.distribution(name)
        except m.PackageNotFoundError:
            continue
        seen[name] = dist.version
        for req in (dist.requires or []):
            if "; extra ==" in req:
                continue
            dep = (
                req.split(";")[0]
                .split("[")[0]
                .split("<")[0]
                .split(">")[0]
                .split("==")[0]
                .split("!=")[0]
                .split("~=")[0]
                .strip()
            )
            if dep:
                stack.append(dep)
    return seen


def write_lock(path: Path, deps: dict[str, str], roots: list[str]):
    header = (
        "# Auto-generated by scripts/_gen_locks.py — the full transitive\n"
        "# closure of the direct deps in the sibling requirements.txt as\n"
        "# resolved on the dev machine at lock time. Regenerate after any\n"
        "# requirements.txt change. Do NOT hand-edit.\n"
        f"# Direct deps: {', '.join(roots)}\n"
    )
    body = "\n".join(f"{k}=={deps[k]}" for k in sorted(deps))
    path.write_text(header + body + "\n", encoding="utf-8")
    print(f"wrote {path}  ({len(deps)} packages)")


def main():
    root_deps = closure(DIRECT_ROOT)
    rag_deps = closure(DIRECT_RAG)
    write_lock(ROOT / "requirements.lock", root_deps, DIRECT_ROOT)
    write_lock(ROOT / "rag_api" / "requirements.lock", rag_deps, DIRECT_RAG)


if __name__ == "__main__":
    main()
